; =============================================================================
; DeepExcel.Setup.iss  —  InnoSetup installer for the DeepExcel Excel COM Add-in
; -----------------------------------------------------------------------------
; Goal: a SINGLE setup.exe the user double-clicks -> installs per-user (no
; admin) -> registers the COM add-in for BOTH 32/64-bit Excel -> done.
;
; This replaces the old "download ZIP, run register-user.ps1" workflow that
; broke for end users (Mark-of-the-Web, missing runtime, wrong bitness,
; hardcoded version, HKLM shadowing, admin prompts).
;
; Build (on Windows, Inno Setup 6+):
;     iscc.exe DeepExcel.Setup.iss
;
; PREREQUISITE: scripts/package_release.py generates deploy/DeepExcel.reg.iss
; (the real assembly version string). Without it, compilation fails on purpose.
;
; Design notes (why each piece exists):
;   * PrivilegesRequired=lowest + DefaultDirName={localappdata} -> no admin.
;   * COM registration is done in [Code], NOT [Registry]. Inno's [Registry]
;     section cannot emit the mscoree InprocServer32 COM shim reliably.
;   * We register HKCU for both the 64-bit view (CLSID) and the 32-bit view
;     (WOW6432Node\CLSID) because AnyCPU loads in both Excel bitnesses.
;   * Assembly version is read from the DLL at BUILD time (DeepExcel.reg.iss),
;     so it can never drift from the hardcoded 0.2.4.0 that broke v0.3-v0.4.
;   * .NET 4.8 and WebView2 are gated; WebView2 bootstrapper is bundled.
; =============================================================================

#pragma include __INCLUDE__ + ";" + SourcePath

; ---- Paths / build inputs -------------------------------------------------
#define PayloadDir "payload\"
#define BuildDir PayloadDir + "Excel\"
#define AddinDLL "DeepExcel.AddIn.dll"
#define DllFullPath BuildDir + AddinDLL
#define AppVersion GetVersionNumbersString(BuildDir + AddinDLL)

; ---- Identity -------------------------------------------------------------
#define AppName "DeepExcel"
#define AppPublisher "DeepExcel"
#define AppURL "https://github.com/1256048998/DeepExcel"
; Stable per-user AppId (HKCU registration -> per-user uninstall key).
#define AppGuid "{C8E2A9F1-7B3C-4D5E-9F0A-1B2C3D4E5F6A}"
#define AppId "{{C8E2A9F1-7B3C-4D5E-9F0A-1B2C3D4E5F6A}"

; ---- COM identities (MUST match ThisAddIn.cs / TaskPaneControl.cs) --------
#define MainClsid "{A1B2C3D4-E5F6-4F4B-9A5F-9B3C1D2E3F4A}"
#define TaskPaneClsid "{B2C3D4E5-F6A7-404B-9A5F-9B3C1D2E3F4B}"
#define MainProgId "DeepExcel.AddIn"
#define TaskPaneProgId "DeepExcel.AddIn.TaskPaneControl"
#define MainClass "DeepExcel.AddIn.ThisAddIn"
#define TaskPaneClass "DeepExcel.AddIn.TaskPaneControl"
; .NET component category GUID (RegAsm writes this; managed COM needs it).
#define DotNetCat "{62C8FE65-4EBB-45E7-B440-6E39B2CDBF29}"
; WebView2 Runtime Evergreen client GUID (used to detect the runtime).
#define WebView2Client "{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}"

; ---- Generated by scripts/package_release.py (assembly version string) -----
; Provides: AssemblyVersion, AssemblyValue
#include "DeepExcel.reg.iss"

[Setup]
AppId={#AppId}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}
DefaultDirName={localappdata}\{#AppName}
DefaultGroupName={#AppName}
AllowNoIcons=yes
OutputDir=..\dist
OutputBaseFilename=DeepExcel.Setup
Compression=lzma
SolidCompression=yes
; Per-user by default; only escalates if the user opts into an all-users path
; (not offered here) or if an old HKLM registration must be cleared.
PrivilegesRequired=lowest
; The add-in is AnyCPU; allow both Office bitnesses on the installing machine.
; The embedded sidecar Python is amd64. 32-bit Office remains supported on a
; 64-bit OS through the WOW registry view and x86 WebView2 loader.
ArchitecturesAllowed=x64compatible arm64
ArchitecturesInstallIn64BitMode=x64compatible arm64
SetupLogging=yes
CloseApplications=yes
RestartApplications=no
CloseApplicationsFilter=EXCEL.EXE,et.exe,wps.exe
; Keep the install dir simple and predictable (no version subfolder).
; WPS resolves the shared Python runtime from this stable per-user location.
DisableDirPage=yes
; Don't let the wizard restart the machine.
RestartIfNeededByRun=no
; Sign the uninstaller + setup binaries via scripts/sign.ps1 (Authenticode).
; The $f placeholder is the file InnoSetup wants signed; sign.ps1 also stamps
; an RFC3161 timestamp so the signature outlives the cert. Set a cert in CI via
; DEEPEXCEL_PFX / DEEPEXCEL_PFX_PASS, DEEPEXCEL_CERT_THUMBPRINT for the
; explicitly labelled internal build, or USE_AZURE_TRUSTED_SIGNING=1.
#if (GetEnv("DEEPEXCEL_PFX") != "") || (GetEnv("DEEPEXCEL_CERT_THUMBPRINT") != "") || (GetEnv("USE_AZURE_TRUSTED_SIGNING") == "1") || (GetEnv("USE_AZURE_TRUSTED_SIGNING") == "true")
SignTool=deepsign
#endif

#if FileExists(SourcePath + "License.rtf")
LicenseFile={#SourcePath}License.rtf
#endif
#if FileExists(SourcePath + "Includes\DeepExcel.ico")
SetupIconFile={#SourcePath}Includes\DeepExcel.ico
UninstallDisplayIcon={#SourcePath}Includes\DeepExcel.ico
#endif

[Languages]
Name: "English"; MessagesFile: "compiler:Default.isl"

[Files]
; Install only the deterministic payload assembled by package_release.py.
Source: "{#BuildDir}*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs
; WPS publish mode expects a folder named <name>_<version> under jsaddons.
Source: "{#PayloadDir}Wps\*"; DestDir: "{userappdata}\kingsoft\wps\jsaddons\DeepExcel_{#AppVersion}"; Flags: ignoreversion recursesubdirs
; package_release.py downloads and validates Microsoft's signed bootstrapper.
Source: "Includes\MicrosoftEdgeWebview2Setup.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall; Check: WebView2NeedsInstall

[Icons]
Name: "{group}\{cm:UninstallProgram,{#AppName}}"; Filename: "{uninstallexe}"
Name: "{group}\{#AppName} 官网"; Filename: "{#AppURL}"
Name: "{group}\手动注册（排错用）"; Filename: "powershell.exe"; Parameters: "-ExecutionPolicy Bypass -File ""{app}\register-user.ps1"""; WorkingDir: "{app}"

[UninstallDelete]
Type: filesandordirs; Name: "{userappdata}\kingsoft\wps\jsaddons\DeepExcel_{#AppVersion}"

[Code]
// ---------------------------------------------------------------------------
// Types / globals
// ---------------------------------------------------------------------------
var
  ExcelEnabled: Boolean;
  ExcelInstalled: Boolean;
  InstallCompleted: Boolean;
  PreviousRegistrationExists: Boolean;
  PreviousMainAssembly: string;
  PreviousMainCodeBase: string;
  PreviousTaskPaneAssembly: string;
  PreviousTaskPaneCodeBase: string;
  PreviousAddinDescription: string;
  PreviousAddinFriendlyName: string;
  PreviousAddinLocation: string;
  PreviousLoadBehavior: Cardinal;
  PreviousCommandLineSafe: Cardinal;

// ---------------------------------------------------------------------------
// .NET 4.8 detection (adapted from Kynosarges DotNetVersion, public domain)
// ---------------------------------------------------------------------------
function IsDotNet48Detected(): Boolean;
var
  install, release: Cardinal;
begin
  Result :=
    RegQueryDWordValue(HKLM, 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', 'Install', install) and
    RegQueryDWordValue(HKLM, 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', 'Release', release) and
    (install = 1) and (release >= 528040);
end;

function IsExcelInstalled(): Boolean;
begin
  Result :=
    RegKeyExists(HKLM, 'SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\excel.exe') or
    RegKeyExists(HKLM, 'SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\App Paths\excel.exe') or
    RegKeyExists(HKCU, 'SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\excel.exe') or
    RegKeyExists(HKLM, 'SOFTWARE\Microsoft\Office\16.0\Excel\InstallRoot') or
    RegKeyExists(HKLM, 'SOFTWARE\WOW6432Node\Microsoft\Office\16.0\Excel\InstallRoot') or
    RegKeyExists(HKLM, 'SOFTWARE\Microsoft\Office\ClickToRun\Configuration');
end;

// ---------------------------------------------------------------------------
// WebView2 Runtime detection
// ---------------------------------------------------------------------------
function IsWebView2Installed(): Boolean;
var
  pv: string;
begin
  Result := False;
  if RegQueryStringValue(HKLM, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\{#WebView2Client}', 'pv', pv) and
     (pv <> '') and (pv <> '0.0.0.0') then Result := True
  else if RegQueryStringValue(HKLM, 'SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{#WebView2Client}', 'pv', pv) and
          (pv <> '') and (pv <> '0.0.0.0') then Result := True
  else if RegQueryStringValue(HKCU, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\{#WebView2Client}', 'pv', pv) and
          (pv <> '') and (pv <> '0.0.0.0') then Result := True
  else if RegQueryStringValue(HKCU, 'SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{#WebView2Client}', 'pv', pv) and
          (pv <> '') and (pv <> '0.0.0.0') then Result := True;
end;

function WebView2NeedsInstall(): Boolean;
begin
  Result := not IsWebView2Installed();
end;

// ---------------------------------------------------------------------------
// HKLM residual detection (legacy machine-wide install via register.ps1)
// ---------------------------------------------------------------------------
function HklmResidualExists(): Boolean;
begin
  Result :=
    RegKeyExists(HKLM, 'SOFTWARE\Classes\CLSID\{#MainClsid}') or
    RegKeyExists(HKLM, 'SOFTWARE\WOW6432Node\Classes\CLSID\{#MainClsid}') or
    RegKeyExists(HKLM, 'SOFTWARE\Classes\CLSID\{#TaskPaneClsid}') or
    RegKeyExists(HKLM, 'SOFTWARE\WOW6432Node\Classes\CLSID\{#TaskPaneClsid}') or
    RegKeyExists(HKLM, 'SOFTWARE\Microsoft\Office\Excel\Addins\{#MainProgId}') or
    RegKeyExists(HKLM, 'SOFTWARE\Microsoft\Office\16.0\Excel\Addins\{#MainProgId}');
end;

// ---------------------------------------------------------------------------
// COM class registration (real 64-bit and 32-bit HKCU registry views)
// ---------------------------------------------------------------------------
procedure RegisterComClassView(const rootKey: Integer; const clsid, progId, dllPath, className,
  assemblyValue, clsidView, progIdView: string);
var
  inprocKey: string;
  versionKey: string;
  codeBase: string;
begin
  inprocKey := clsidView + '\InprocServer32';
  versionKey := inprocKey + '\{#AssemblyVersion}';
  codeBase := dllPath;
  StringChangeEx(codeBase, '\', '/', True);
  codeBase := 'file:///' + codeBase;

  // The CLSID is exclusively owned by DeepExcel. Recreate InprocServer32 so
  // an upgrade cannot leave an older assembly-version subkey behind.
  RegDeleteKeyIncludingSubkeys(rootKey, inprocKey);

  // CLSID default = class name
  if not RegWriteStringValue(rootKey, clsidView, '', className) then
    RaiseException('Cannot register COM class ' + className + '.');

  // InprocServer32 (the mscoree shim that loads the managed DLL)
  if not RegWriteStringValue(rootKey, inprocKey, '', 'mscoree.dll') then RaiseException('Cannot write COM server.');
  if not RegWriteStringValue(rootKey, inprocKey, 'Assembly', assemblyValue) then RaiseException('Cannot write COM assembly.');
  if not RegWriteStringValue(rootKey, inprocKey, 'Class', className) then RaiseException('Cannot write COM class.');
  if not RegWriteStringValue(rootKey, inprocKey, 'CodeBase', codeBase) then RaiseException('Cannot write COM CodeBase.');
  if not RegWriteStringValue(rootKey, inprocKey, 'RuntimeVersion', 'v4.0.30319') then RaiseException('Cannot write COM runtime.');
  if not RegWriteStringValue(rootKey, inprocKey, 'ThreadingModel', 'Both') then RaiseException('Cannot write COM threading model.');

  // Match RegAsm's canonical versioned registration exactly.
  if not RegWriteStringValue(rootKey, versionKey, 'Assembly', assemblyValue) then RaiseException('Cannot write versioned COM assembly.');
  if not RegWriteStringValue(rootKey, versionKey, 'Class', className) then RaiseException('Cannot write versioned COM class.');
  if not RegWriteStringValue(rootKey, versionKey, 'CodeBase', codeBase) then RaiseException('Cannot write versioned COM CodeBase.');
  if not RegWriteStringValue(rootKey, versionKey, 'RuntimeVersion', 'v4.0.30319') then RaiseException('Cannot write versioned COM runtime.');

  // .NET component category (without it some Office builds ignore the CLSID)
  if not RegWriteStringValue(rootKey, clsidView + '\Implemented Categories\{#DotNetCat}', '', '') then
    RaiseException('Cannot register .NET COM category.');

  // ProgId reverse mapping (CLSID -> ProgID)
  if not RegWriteStringValue(rootKey, clsidView + '\ProgId', '', progId) then
    RaiseException('Cannot register COM ProgID mapping.');

  // ProgID key -> CLSID
  if not RegWriteStringValue(rootKey, progIdView, '', className) then RaiseException('Cannot register ProgID.');
  if not RegWriteStringValue(rootKey, progIdView + '\CLSID', '', clsid) then RaiseException('Cannot register ProgID CLSID.');
end;

procedure RegisterComClass(const clsid, progId, dllPath, className, assemblyValue: string);
begin
  // 64-bit view (native CLSID)
  RegisterComClassView(HKCU64, clsid, progId, dllPath, className, assemblyValue,
    'Software\Classes\CLSID\' + clsid, 'Software\Classes\' + progId);
  // 32-bit view read by 32-bit Excel. HKCU32 is essential: spelling a
  // WOW6432Node path under HKCU64 does not register the class in this view.
  RegisterComClassView(HKCU32, clsid, progId, dllPath, className, assemblyValue,
    'Software\Classes\CLSID\' + clsid, 'Software\Classes\' + progId);
end;

procedure UnregisterComClass(const clsid, progId: string);
begin
  RegDeleteKeyIncludingSubkeys(HKCU64, 'Software\Classes\CLSID\' + clsid);
  RegDeleteKeyIncludingSubkeys(HKCU32, 'Software\Classes\CLSID\' + clsid);
  RegDeleteKeyIncludingSubkeys(HKCU64, 'Software\Classes\' + progId);
  RegDeleteKeyIncludingSubkeys(HKCU32, 'Software\Classes\' + progId);
  // Clean the invalid legacy paths written by releases before 0.4.17.
  RegDeleteKeyIncludingSubkeys(HKCU64, 'Software\Classes\WOW6432Node\CLSID\' + clsid);
  RegDeleteKeyIncludingSubkeys(HKCU64, 'Software\Classes\WOW6432Node\' + progId);
end;

// ---------------------------------------------------------------------------
// Excel COM Add-ins entry + resiliency (so Excel won't soft-disable us)
// ---------------------------------------------------------------------------
procedure RegisterExcelAddIn(const progId, friendlyName, dllPath: string);
var
  addinKey: string;
  resiliencyKey: string;
begin
  addinKey := 'Software\Microsoft\Office\Excel\Addins\' + progId;
  RegWriteStringValue(HKCU, addinKey, 'Description', friendlyName);
  RegWriteStringValue(HKCU, addinKey, 'FriendlyName', friendlyName);
  RegWriteDWordValue(HKCU, addinKey, 'LoadBehavior', 3);
  RegWriteDWordValue(HKCU, addinKey, 'CommandLineSafe', 0);
  RegWriteStringValue(HKCU, addinKey, 'Location', dllPath);

  // DoNotDisableAddinList: prevents Excel from flipping LoadBehavior to 2
  // after any startup hiccup and silently hiding the add-in.
  resiliencyKey := 'Software\Microsoft\Office\16.0\Excel\Resiliency\DoNotDisableAddinList';
  RegWriteDWordValue(HKCU, resiliencyKey, progId, 1);
end;

procedure UnregisterExcelAddIn(const progId: string);
begin
  RegDeleteKeyIncludingSubkeys(HKCU, 'Software\Microsoft\Office\Excel\Addins\' + progId);
  RegDeleteKeyIncludingSubkeys(HKCU, 'Software\Microsoft\Office\16.0\Excel\Addins\' + progId);
  RegDeleteValue(HKCU, 'Software\Microsoft\Office\16.0\Excel\Resiliency\DoNotDisableAddinList', progId);
end;

procedure SnapshotPreviousExcelRegistration();
var
  addinKey: string;
begin
  addinKey := 'Software\Microsoft\Office\Excel\Addins\{#MainProgId}';
  PreviousRegistrationExists :=
    RegQueryStringValue(
      HKCU, 'Software\Classes\CLSID\{#MainClsid}\InprocServer32',
      'Assembly', PreviousMainAssembly) and
    RegQueryStringValue(
      HKCU, 'Software\Classes\CLSID\{#MainClsid}\InprocServer32',
      'CodeBase', PreviousMainCodeBase) and
    RegQueryStringValue(
      HKCU, 'Software\Classes\CLSID\{#TaskPaneClsid}\InprocServer32',
      'Assembly', PreviousTaskPaneAssembly) and
    RegQueryStringValue(
      HKCU, 'Software\Classes\CLSID\{#TaskPaneClsid}\InprocServer32',
      'CodeBase', PreviousTaskPaneCodeBase) and
    RegQueryStringValue(HKCU, addinKey, 'Description', PreviousAddinDescription) and
    RegQueryStringValue(HKCU, addinKey, 'FriendlyName', PreviousAddinFriendlyName) and
    RegQueryStringValue(HKCU, addinKey, 'Location', PreviousAddinLocation) and
    RegQueryDWordValue(HKCU, addinKey, 'LoadBehavior', PreviousLoadBehavior) and
    RegQueryDWordValue(HKCU, addinKey, 'CommandLineSafe', PreviousCommandLineSafe);
end;

procedure RestorePreviousExcelRegistration();
var
  addinKey: string;
begin
  RegisterComClass(
    '{#MainClsid}', '{#MainProgId}', PreviousMainCodeBase,
    '{#MainClass}', PreviousMainAssembly);
  RegisterComClass(
    '{#TaskPaneClsid}', '{#TaskPaneProgId}', PreviousTaskPaneCodeBase,
    '{#TaskPaneClass}', PreviousTaskPaneAssembly);

  RegisterExcelAddIn(
    '{#MainProgId}', PreviousAddinFriendlyName, PreviousAddinLocation);
  addinKey := 'Software\Microsoft\Office\Excel\Addins\{#MainProgId}';
  RegWriteStringValue(HKCU, addinKey, 'Description', PreviousAddinDescription);
  RegWriteDWordValue(HKCU, addinKey, 'LoadBehavior', PreviousLoadBehavior);
  RegWriteDWordValue(HKCU, addinKey, 'CommandLineSafe', PreviousCommandLineSafe);
end;

procedure RequireRegistryString(const rootKey: Integer; const key, name, expected: string);
var
  actual: string;
begin
  if (not RegQueryStringValue(rootKey, key, name, actual)) or (actual <> expected) then
    RaiseException('DeepExcel registry verification failed: HKCU\' + key + ' [' + name + ']');
end;

procedure RequireRegistryDWord(const key, name: string; expected: Cardinal);
var
  actual: Cardinal;
begin
  if (not RegQueryDWordValue(HKCU, key, name, actual)) or (actual <> expected) then
    RaiseException('DeepExcel registry verification failed: HKCU\' + key + ' [' + name + ']');
end;

procedure VerifyDeepExcelRegistration();
var
  dllPath: string;
begin
  dllPath := ExpandConstant('{app}') + '\' + '{#AddinDLL}';
  StringChangeEx(dllPath, '\', '/', True);
  dllPath := 'file:///' + dllPath;
  RequireRegistryString(HKCU64, 'Software\Classes\CLSID\{#MainClsid}\InprocServer32', 'CodeBase', dllPath);
  RequireRegistryString(HKCU32, 'Software\Classes\CLSID\{#MainClsid}\InprocServer32', 'CodeBase', dllPath);
  RequireRegistryString(HKCU64, 'Software\Classes\CLSID\{#MainClsid}\InprocServer32\{#AssemblyVersion}', 'CodeBase', dllPath);
  RequireRegistryString(HKCU32, 'Software\Classes\CLSID\{#MainClsid}\InprocServer32\{#AssemblyVersion}', 'CodeBase', dllPath);
  RequireRegistryString(HKCU64, 'Software\Classes\CLSID\{#TaskPaneClsid}\InprocServer32', 'CodeBase', dllPath);
  RequireRegistryString(HKCU32, 'Software\Classes\CLSID\{#TaskPaneClsid}\InprocServer32', 'CodeBase', dllPath);
  RequireRegistryString(HKCU64, 'Software\Classes\CLSID\{#TaskPaneClsid}\InprocServer32\{#AssemblyVersion}', 'CodeBase', dllPath);
  RequireRegistryString(HKCU32, 'Software\Classes\CLSID\{#TaskPaneClsid}\InprocServer32\{#AssemblyVersion}', 'CodeBase', dllPath);
  RequireRegistryString(HKCU64, 'Software\Classes\{#MainProgId}\CLSID', '', '{#MainClsid}');
  RequireRegistryString(HKCU32, 'Software\Classes\{#MainProgId}\CLSID', '', '{#MainClsid}');
  RequireRegistryDWord('Software\Microsoft\Office\Excel\Addins\{#MainProgId}', 'LoadBehavior', 3);
end;

procedure RunAndRequire(const fileName, parameters, description: string);
var
  resultCode: Integer;
begin
  if IsUninstaller() then
    UninstallProgressForm.StatusLabel.Caption := description
  else
    WizardForm.StatusLabel.Caption := description;
  if (not Exec(fileName, parameters, '', SW_HIDE, ewWaitUntilTerminated, resultCode)) or
     (resultCode <> 0) then
    RaiseException(description + ' failed (exit code ' + IntToStr(resultCode) + ').');
end;

function PowerShellPath(): string;
begin
  Result := ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe');
end;

function MoveFileEx(existingFile, newFile: string; flags: Cardinal): Boolean;
  external 'MoveFileExW@kernel32.dll stdcall';

procedure UpdateWpsManifest(const mode: string);
var
  addinRoot, manifestPath, temporaryPath, backupPath: string;
  originalHash: string;
  originalExists, existsNow: Boolean;
  document, validationDocument, rootNode, nodes, entry: Variant;
begin
  addinRoot := ExpandConstant('{userappdata}\kingsoft\wps\jsaddons');
  manifestPath := addinRoot + '\publish.xml';
  temporaryPath := addinRoot + '\.publish.deepexcel.tmp';
  backupPath := manifestPath + '.bak';
  ForceDirectories(addinRoot);

  originalExists := FileExists(manifestPath);
  if originalExists then
    originalHash := GetSHA256OfFile(manifestPath)
  else
    originalHash := '';

  document := CreateOleObject('MSXML2.DOMDocument.6.0');
  document.async := False;
  document.resolveExternals := False;
  document.preserveWhiteSpace := False;
  if originalExists then
  begin
    document.load(manifestPath);
    if document.parseError.errorCode <> 0 then
    begin
      CopyFile(manifestPath, manifestPath + '.invalid.bak', False);
      RaiseException('Existing WPS publish.xml is invalid: ' + document.parseError.reason);
    end;
  end
  else
  begin
    document.loadXML('<?xml version="1.0" encoding="utf-8"?><jsplugins/>');
  end;

  rootNode := document.documentElement;
  if CompareText(rootNode.nodeName, 'jsplugins') <> 0 then
    RaiseException('Unexpected WPS manifest root (expected jsplugins).');

  nodes := rootNode.selectNodes('*[@name="DeepExcel"]');
  while nodes.length > 0 do
  begin
    rootNode.removeChild(nodes.item(0));
    nodes := rootNode.selectNodes('*[@name="DeepExcel"]');
  end;

  if CompareText(mode, 'Install') = 0 then
  begin
    entry := document.createElement('jsplugin');
    entry.setAttribute('name', 'DeepExcel');
    entry.setAttribute('type', 'et');
    entry.setAttribute('url', 'DeepExcel_{#AppVersion}');
    entry.setAttribute('version', '{#AppVersion}');
    entry.setAttribute('enable', 'enable_dev');
    entry.setAttribute('install', 'null');
    entry.setAttribute('customDomain', '');
    rootNode.appendChild(entry);
  end;

  DeleteFile(temporaryPath);
  document.save(temporaryPath);
  if not FileExists(temporaryPath) then
    RaiseException('WPS manifest temporary file was not created.');

  validationDocument := CreateOleObject('MSXML2.DOMDocument.6.0');
  validationDocument.async := False;
  validationDocument.resolveExternals := False;
  validationDocument.load(temporaryPath);
  if validationDocument.parseError.errorCode <> 0 then
  begin
    DeleteFile(temporaryPath);
    RaiseException('Generated WPS manifest is invalid: ' + validationDocument.parseError.reason);
  end;

  existsNow := FileExists(manifestPath);
  if existsNow <> originalExists then
  begin
    DeleteFile(temporaryPath);
    RaiseException('WPS publish.xml changed during update; please retry.');
  end;
  if originalExists and (GetSHA256OfFile(manifestPath) <> originalHash) then
  begin
    DeleteFile(temporaryPath);
    RaiseException('WPS publish.xml was modified by another process; please retry.');
  end;

  if originalExists and (not CopyFile(manifestPath, backupPath, False)) then
  begin
    DeleteFile(temporaryPath);
    RaiseException('Cannot back up WPS publish.xml.');
  end;

  { MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH }
  if not MoveFileEx(temporaryPath, manifestPath, 1 or 8) then
  begin
    DeleteFile(temporaryPath);
    RaiseException('Cannot atomically replace WPS publish.xml.');
  end;
end;

// ---------------------------------------------------------------------------
// Full register / unregister
// ---------------------------------------------------------------------------
procedure RegisterDeepExcel();
var
  dllPath: string;
begin
  dllPath := ExpandConstant('{app}') + '\' + '{#AddinDLL}';
  RegisterComClass('{#MainClsid}', '{#MainProgId}', dllPath, '{#MainClass}', '{#AssemblyValue}');
  RegisterComClass('{#TaskPaneClsid}', '{#TaskPaneProgId}', dllPath, '{#TaskPaneClass}', '{#AssemblyValue}');
  RegisterExcelAddIn('{#MainProgId}', '{#AppName} AI AddIn', dllPath);
end;

procedure UnregisterDeepExcel();
begin
  UnregisterExcelAddIn('{#MainProgId}');
  UnregisterComClass('{#MainClsid}', '{#MainProgId}');
  UnregisterComClass('{#TaskPaneClsid}', '{#TaskPaneProgId}');
end;

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------
function InitializeSetup(): Boolean;
var
  ec: Integer;
begin
  // Always register Excel. Some enterprise/MSI/non-default Office installs
  // omit App Paths; the old detection then silently skipped Excel while Setup
  // still reported success. Detection now controls only eager prerequisites.
  ExcelInstalled := IsExcelInstalled();
  ExcelEnabled := True;
  if ExcelInstalled then
    Log('Excel detected: True')
  else
    Log('Excel detected: False; Excel registration will still be installed.');
  SnapshotPreviousExcelRegistration();
  if ExcelInstalled and (not IsDotNet48Detected()) then
  begin
    MsgBox('DeepExcel 需要 .NET Framework 4.8。' + #13#10 +
           '请先安装 .NET 4.8 后再运行本安装程序。', mbCriticalError, MB_OK);
    ShellExec('open', 'https://dotnet.microsoft.com/download/dotnet-framework/net48', '', '', SW_SHOW, ewNoWait, ec);
    Result := False;
    Exit;
  end;

  // 2) Old machine-wide registration shadows the per-user one. Do not continue
  //    unless this process can clean it after the user accepts the wizard.
  if HklmResidualExists() then
  begin
    MsgBox('检测到旧版“机器级(管理员)”注册残留，它会覆盖本次用户级注册。' + #13#10 +
           '请让管理员先卸载旧版或清理旧版机器级注册，然后由当前用户正常运行本安装程序。' + #13#10 +
           '不要用另一个管理员账户运行本安装程序，否则会安装到错误的用户账户。', mbCriticalError, MB_OK);
    Result := False;
    Exit;
  end;

  // 3) WebView2 runtime warning (install is attempted after files are copied).
  if ExcelInstalled and (not IsWebView2Installed()) then
    MsgBox('未检测到 WebView2 运行时，安装程序将自动为您安装（需联网）。' + #13#10 +
           '若离线环境安装失败，请先手动安装“Microsoft Edge WebView2 Runtime”。', mbInformation, MB_OK);

  Result := True;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  errorMessage: string;
  wpsActivated: Boolean;
begin
  if CurStep = ssPostInstall then
  begin
    wpsActivated := False;
    try
      if ExcelEnabled then
      begin
        if ExcelInstalled and WebView2NeedsInstall() then
          RunAndRequire(
            ExpandConstant('{tmp}\MicrosoftEdgeWebview2Setup.exe'),
            '/silent /install',
            '正在安装 WebView2 运行时');
        if ExcelInstalled and (not IsWebView2Installed()) then
          RaiseException('WebView2 Runtime installation did not complete successfully.');

        RegisterDeepExcel();
        VerifyDeepExcelRegistration();
        RunAndRequire(
          PowerShellPath(),
          '-NoProfile -NonInteractive -ExecutionPolicy Bypass -File "' +
            ExpandConstant('{app}\register-user.ps1') + '" -RepairOnly',
          '正在修复 Excel 加载项状态');
        RunAndRequire(
          ExpandConstant('{win}\SysWOW64\WindowsPowerShell\v1.0\powershell.exe'),
          '-NoProfile -NonInteractive -ExecutionPolicy Bypass -File "' +
            ExpandConstant('{app}\register-user.ps1') + '" -ActivationOnly',
          '正在验证 32 位 Excel 加载器');
        VerifyDeepExcelRegistration();
      end;

      // WPS activation is deliberately last: all following statements are
      // non-failing bookkeeping, so a committed publish.xml never points at
      // files that a later setup error rolls back.
      WizardForm.StatusLabel.Caption := '正在启用 WPS 表格加载项';
      UpdateWpsManifest('Install');
      wpsActivated := True;
    except
      errorMessage := GetExceptionMessage();
      if wpsActivated then
        try UpdateWpsManifest('Uninstall'); except end;
      if ExcelEnabled then
      begin
        if PreviousRegistrationExists then
          RestorePreviousExcelRegistration()
        else
          UnregisterDeepExcel();
      end;
      RaiseException(errorMessage);
    end;
  end
  else if CurStep = ssDone then
    InstallCompleted := True;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usUninstall then
  begin
    UninstallProgressForm.StatusLabel.Caption := '正在移除 WPS 表格加载项';
    UpdateWpsManifest('Uninstall');
    UnregisterDeepExcel();
  end;
end;

procedure DeinitializeSetup();
begin
  // Friendly final note (only on a successful, non-silent install).
  if InstallCompleted and (not WizardSilent) and (not IsUninstaller()) then
    MsgBox('DeepExcel 安装完成！' + #13#10 + #13#10 +
           '请关闭并重新打开 Excel 或 WPS 表格，' + #13#10 +
           '在功能区（Ribbon）中找到“DeepExcel”选项卡即可使用。', mbInformation, MB_OK);
end;
