; =============================================================================
; DeepExcel.Setup.iss  —  InnoSetup installer for the DeepExcel Excel COM Add-in
; -----------------------------------------------------------------------------
; Goal: a SINGLE setup.exe the user double-clicks -> installs per-user (no
; admin) -> registers the COM add-in for BOTH 32/64-bit Excel -> done.
;
; This replaces the old "download ZIP, run register-user.ps1" workflow that
; broke for end users (Mark-of-the-Web, missing runtime, wrong bitness,
; hardcoded version, HKLM shadowing, admin prompts).
;
; Build (on Windows, Inno Setup 6+):
;     iscc.exe DeepExcel.Setup.iss
;
; PREREQUISITE: scripts/package_release.py generates deploy/DeepExcel.reg.iss
; (the real assembly version string). Without it, compilation fails on purpose.
;
; Design notes (why each piece exists):
;   * PrivilegesRequired=lowest + DefaultDirName={localappdata} -> no admin.
;   * COM registration is done in [Code], NOT [Registry]. Inno's [Registry]
;     section cannot emit the mscoree InprocServer32 COM shim reliably.
;   * We register HKCU for both the 64-bit view (CLSID) and the 32-bit view
;     (WOW6432Node\CLSID) because AnyCPU loads in both Excel bitnesses.
;   * Assembly version is read from the DLL at BUILD time (DeepExcel.reg.iss),
;     so it can never drift from the hardcoded 0.2.4.0 that broke v0.3-v0.4.
;   * .NET 4.8 and WebView2 are gated; WebView2 bootstrapper is bundled.
; =============================================================================

#pragma include __INCLUDE__ + ";" + SourcePath

; ---- Paths / build inputs -------------------------------------------------
#define PayloadDir "payload\"
#define BuildDir PayloadDir + "Excel\"
#define AddinDLL "DeepExcel.AddIn.dll"
#define DllFullPath BuildDir + AddinDLL
#define AppVersion GetVersionNumbersString(BuildDir + AddinDLL)

; ---- Identity -------------------------------------------------------------
#define AppName "DeepExcel"
#define AppPublisher "DeepExcel"
#define AppURL "https://github.com/1256048998/DeepExcel"
; Stable per-user AppId (HKCU registration -> per-user uninstall key).
#define AppGuid "{C8E2A9F1-7B3C-4D5E-9F0A-1B2C3D4E5F6A}"
#define AppId "{{C8E2A9F1-7B3C-4D5E-9F0A-1B2C3D4E5F6A}"

; ---- COM identities (MUST match ThisAddIn.cs / TaskPaneControl.cs) --------
#define MainClsid "{A1B2C3D4-E5F6-4F4B-9A5F-9B3C1D2E3F4A}"
#define TaskPaneClsid "{B2C3D4E5-F6A7-404B-9A5F-9B3C1D2E3F4B}"
#define MainProgId "DeepExcel.AddIn"
#define TaskPaneProgId "DeepExcel.AddIn.TaskPaneControl"
#define MainClass "DeepExcel.AddIn.ThisAddIn"
#define TaskPaneClass "DeepExcel.AddIn.TaskPaneControl"
; .NET component category GUID (RegAsm writes this; managed COM needs it).
#define DotNetCat "{62C8FE65-4EBB-45E7-B440-6E39B2CDBF29}"
; WebView2 Runtime Evergreen client GUID (used to detect the runtime).
#define WebView2Client "{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}"

; ---- Generated by scripts/package_release.py (assembly version string) -----
; Provides: AssemblyVersion, AssemblyValue
#include "DeepExcel.reg.iss"

[Setup]
AppId={#AppId}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}
DefaultDirName={localappdata}\{#AppName}
DefaultGroupName={#AppName}
AllowNoIcons=yes
OutputDir=..\dist
OutputBaseFilename=DeepExcel.Setup
Compression=lzma
SolidCompression=yes
; Per-user by default; only escalates if the user opts into an all-users path
; (not offered here) or if an old HKLM registration must be cleared.
PrivilegesRequired=lowest
; The add-in is AnyCPU; allow both Office bitnesses on the installing machine.
; The embedded sidecar Python is amd64. 32-bit Office remains supported on a
; 64-bit OS through the WOW registry view and x86 WebView2 loader.
ArchitecturesAllowed=x64compatible arm64
ArchitecturesInstallIn64BitMode=x64compatible arm64
SetupLogging=yes
CloseApplications=yes
RestartApplications=no
CloseApplicationsFilter=EXCEL.EXE,et.exe,wps.exe
; Keep the install dir simple and predictable (no version subfolder).
; WPS resolves the shared Python runtime from this stable per-user location.
DisableDirPage=yes
; Don't let the wizard restart the machine.
RestartIfNeededByRun=no
; Sign the uninstaller + setup binaries via scripts/sign.ps1 (Authenticode).
; The $f placeholder is the file InnoSetup wants signed; sign.ps1 also stamps
; an RFC3161 timestamp so the signature outlives the cert. Set a cert in CI via
; DEEPEXCEL_PFX / DEEPEXCEL_PFX_PASS or USE_AZURE_TRUSTED_SIGNING=1.
;
; DeepExcel currently ships UNSIGNED: no certificate has been purchased, and
; self-signing was removed on 2026-09-12 because it required users to trust a
; private root CA. Integrity is published as dist/SHA256SUMS.txt instead.
; Signing remains fully wired so a future certificate is an env-var change.
#if (GetEnv("DEEPEXCEL_PFX") != "") || (GetEnv("USE_AZURE_TRUSTED_SIGNING") == "1") || (GetEnv("USE_AZURE_TRUSTED_SIGNING") == "true")
SignTool=deepsign
#endif

#if FileExists(SourcePath + "License.rtf")
LicenseFile={#SourcePath}License.rtf
#endif
#if FileExists(SourcePath + "Includes\DeepExcel.ico")
SetupIconFile={#SourcePath}Includes\DeepExcel.ico
UninstallDisplayIcon={#SourcePath}Includes\DeepExcel.ico
#endif

[Languages]
Name: "English"; MessagesFile: "compiler:Default.isl"

[Files]
; Install only the deterministic payload assembled by package_release.py.
Source: "{#BuildDir}*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs
; WPS publish mode expects a folder named <name>_<version> under jsaddons.
Source: "{#PayloadDir}Wps\*"; DestDir: "{userappdata}\kingsoft\wps\jsaddons\DeepExcel_{#AppVersion}"; Flags: ignoreversion recursesubdirs
; package_release.py downloads and validates Microsoft's signed bootstrapper.
Source: "Includes\MicrosoftEdgeWebview2Setup.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall; Check: WebView2NeedsInstall

[Icons]
Name: "{group}\{cm:UninstallProgram,{#AppName}}"; Filename: "{uninstallexe}"
Name: "{group}\{#AppName} 官网"; Filename: "{#AppURL}"
; One entry point for "Excel 里没有 DeepExcel 选项卡". Double-clicking it opens a
; window that diagnoses on load; the old shortcut launched a raw PowerShell
; console, which most users close before reading.
Name: "{group}\{#AppName} 诊断与修复"; Filename: "{app}\DeepExcel.Repair.exe"; WorkingDir: "{app}"

[UninstallDelete]
Type: filesandordirs; Name: "{userappdata}\kingsoft\wps\jsaddons\DeepExcel_{#AppVersion}"
; Staged update packages. An installer is tens of megabytes, and leaving one
; behind after an uninstall is the kind of thing users find months later.
; Configuration and credentials under {userappdata}\DeepExcel are deliberately
; left alone -- reinstalling should not mean setting up API keys again.
Type: filesandordirs; Name: "{localappdata}\DeepExcel\updates"

[Code]
// ---------------------------------------------------------------------------
// Types / globals
// ---------------------------------------------------------------------------
var
  ExcelEnabled: Boolean;
  ExcelInstalled: Boolean;
  InstallCompleted: Boolean;
  PostInstallFailed: Boolean;
  PostInstallError: string;
  PreviousRegistrationExists: Boolean;
  PreviousMainAssembly: string;
  PreviousMainCodeBase: string;
  PreviousTaskPaneAssembly: string;
  PreviousTaskPaneCodeBase: string;
  PreviousAddinDescription: string;
  PreviousAddinFriendlyName: string;
  PreviousAddinLocation: string;
  PreviousLoadBehavior: Cardinal;
  PreviousCommandLineSafe: Cardinal;

// ---------------------------------------------------------------------------
// .NET 4.8 detection (adapted from Kynosarges DotNetVersion, public domain)
// ---------------------------------------------------------------------------
function IsDotNet48Detected(): Boolean;
var
  install, release: Cardinal;
begin
  Result :=
    RegQueryDWordValue(HKLM, 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', 'Install', install) and
    RegQueryDWordValue(HKLM, 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', 'Release', release) and
    (install = 1) and (release >= 528040);
end;

function IsExcelInstalled(): Boolean;
begin
  Result :=
    RegKeyExists(HKLM, 'SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\excel.exe') or
    RegKeyExists(HKLM, 'SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\App Paths\excel.exe') or
    RegKeyExists(HKCU, 'SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\excel.exe') or
    RegKeyExists(HKLM, 'SOFTWARE\Microsoft\Office\16.0\Excel\InstallRoot') or
    RegKeyExists(HKLM, 'SOFTWARE\WOW6432Node\Microsoft\Office\16.0\Excel\InstallRoot') or
    RegKeyExists(HKLM, 'SOFTWARE\Microsoft\Office\ClickToRun\Configuration');
end;

// ---------------------------------------------------------------------------
// WebView2 Runtime detection
// ---------------------------------------------------------------------------
function IsWebView2Installed(): Boolean;
var
  pv: string;
begin
  Result := False;
  if RegQueryStringValue(HKLM, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\{#WebView2Client}', 'pv', pv) and
     (pv <> '') and (pv <> '0.0.0.0') then Result := True
  else if RegQueryStringValue(HKLM, 'SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{#WebView2Client}', 'pv', pv) and
          (pv <> '') and (pv <> '0.0.0.0') then Result := True
  else if RegQueryStringValue(HKCU, 'SOFTWARE\Microsoft\EdgeUpdate\Clients\{#WebView2Client}', 'pv', pv) and
          (pv <> '') and (pv <> '0.0.0.0') then Result := True
  else if RegQueryStringValue(HKCU, 'SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{#WebView2Client}', 'pv', pv) and
          (pv <> '') and (pv <> '0.0.0.0') then Result := True;
end;

function WebView2NeedsInstall(): Boolean;
begin
  Result := not IsWebView2Installed();
end;

// ---------------------------------------------------------------------------
// HKLM residual detection (legacy machine-wide install via register.ps1)
// ---------------------------------------------------------------------------
function HklmResidualExists(): Boolean;
begin
  Result :=
    RegKeyExists(HKLM, 'SOFTWARE\Classes\CLSID\{#MainClsid}') or
    RegKeyExists(HKLM, 'SOFTWARE\WOW6432Node\Classes\CLSID\{#MainClsid}') or
    RegKeyExists(HKLM, 'SOFTWARE\Classes\CLSID\{#TaskPaneClsid}') or
    RegKeyExists(HKLM, 'SOFTWARE\WOW6432Node\Classes\CLSID\{#TaskPaneClsid}') or
    RegKeyExists(HKLM, 'SOFTWARE\Microsoft\Office\Excel\Addins\{#MainProgId}') or
    RegKeyExists(HKLM, 'SOFTWARE\Microsoft\Office\16.0\Excel\Addins\{#MainProgId}');
end;

// ---------------------------------------------------------------------------
// COM class registration (real 64-bit and 32-bit HKCU registry views)
// ---------------------------------------------------------------------------
procedure RegisterComClassView(const rootKey: Integer; const clsid, progId, dllPath, className,
  assemblyValue, clsidView, progIdView: string);
var
  inprocKey: string;
  versionKey: string;
  codeBase: string;
begin
  inprocKey := clsidView + '\InprocServer32';
  versionKey := inprocKey + '\{#AssemblyVersion}';
  codeBase := dllPath;
  StringChangeEx(codeBase, '\', '/', True);
  codeBase := 'file:///' + codeBase;

  // The CLSID is exclusively owned by DeepExcel. Recreate InprocServer32 so
  // an upgrade cannot leave an older assembly-version subkey behind.
  RegDeleteKeyIncludingSubkeys(rootKey, inprocKey);

  // CLSID default = class name
  if not RegWriteStringValue(rootKey, clsidView, '', className) then
    RaiseException('Cannot register COM class ' + className + '.');

  // InprocServer32 (the mscoree shim that loads the managed DLL)
  if not RegWriteStringValue(rootKey, inprocKey, '', 'mscoree.dll') then RaiseException('Cannot write COM server.');
  if not RegWriteStringValue(rootKey, inprocKey, 'Assembly', assemblyValue) then RaiseException('Cannot write COM assembly.');
  if not RegWriteStringValue(rootKey, inprocKey, 'Class', className) then RaiseException('Cannot write COM class.');
  if not RegWriteStringValue(rootKey, inprocKey, 'CodeBase', codeBase) then RaiseException('Cannot write COM CodeBase.');
  if not RegWriteStringValue(rootKey, inprocKey, 'RuntimeVersion', 'v4.0.30319') then RaiseException('Cannot write COM runtime.');
  if not RegWriteStringValue(rootKey, inprocKey, 'ThreadingModel', 'Both') then RaiseException('Cannot write COM threading model.');

  // Match RegAsm's canonical versioned registration exactly.
  if not RegWriteStringValue(rootKey, versionKey, 'Assembly', assemblyValue) then RaiseException('Cannot write versioned COM assembly.');
  if not RegWriteStringValue(rootKey, versionKey, 'Class', className) then RaiseException('Cannot write versioned COM class.');
  if not RegWriteStringValue(rootKey, versionKey, 'CodeBase', codeBase) then RaiseException('Cannot write versioned COM CodeBase.');
  if not RegWriteStringValue(rootKey, versionKey, 'RuntimeVersion', 'v4.0.30319') then RaiseException('Cannot write versioned COM runtime.');

  // .NET component category (without it some Office builds ignore the CLSID)
  if not RegWriteStringValue(rootKey, clsidView + '\Implemented Categories\{#DotNetCat}', '', '') then
    RaiseException('Cannot register .NET COM category.');

  // ProgId reverse mapping (CLSID -> ProgID)
  if not RegWriteStringValue(rootKey, clsidView + '\ProgId', '', progId) then
    RaiseException('Cannot register COM ProgID mapping.');

  // ProgID key -> CLSID
  if not RegWriteStringValue(rootKey, progIdView, '', className) then RaiseException('Cannot register ProgID.');
  if not RegWriteStringValue(rootKey, progIdView + '\CLSID', '', clsid) then RaiseException('Cannot register ProgID CLSID.');
end;

procedure RegisterComClass(const clsid, progId, dllPath, className, assemblyValue: string);
begin
  // 64-bit view (native CLSID)
  RegisterComClassView(HKCU64, clsid, progId, dllPath, className, assemblyValue,
    'Software\Classes\CLSID\' + clsid, 'Software\Classes\' + progId);
  // 32-bit view read by 32-bit Excel. HKCU32 is essential: spelling a
  // WOW6432Node path under HKCU64 does not register the class in this view.
  RegisterComClassView(HKCU32, clsid, progId, dllPath, className, assemblyValue,
    'Software\Classes\CLSID\' + clsid, 'Software\Classes\' + progId);
end;

procedure UnregisterComClass(const clsid, progId: string);
begin
  RegDeleteKeyIncludingSubkeys(HKCU64, 'Software\Classes\CLSID\' + clsid);
  RegDeleteKeyIncludingSubkeys(HKCU32, 'Software\Classes\CLSID\' + clsid);
  RegDeleteKeyIncludingSubkeys(HKCU64, 'Software\Classes\' + progId);
  RegDeleteKeyIncludingSubkeys(HKCU32, 'Software\Classes\' + progId);
  // Clean the invalid legacy paths written by releases before 0.4.17.
  RegDeleteKeyIncludingSubkeys(HKCU64, 'Software\Classes\WOW6432Node\CLSID\' + clsid);
  RegDeleteKeyIncludingSubkeys(HKCU64, 'Software\Classes\WOW6432Node\' + progId);
end;

// ---------------------------------------------------------------------------
// Excel COM Add-ins entry + resiliency (so Excel won't soft-disable us)
// ---------------------------------------------------------------------------
procedure RegisterExcelAddIn(const progId, friendlyName, dllPath: string);
var
  addinKey: string;
  resiliencyKey: string;
begin
  addinKey := 'Software\Microsoft\Office\Excel\Addins\' + progId;
  RegWriteStringValue(HKCU, addinKey, 'Description', friendlyName);
  RegWriteStringValue(HKCU, addinKey, 'FriendlyName', friendlyName);
  RegWriteDWordValue(HKCU, addinKey, 'LoadBehavior', 3);
  RegWriteDWordValue(HKCU, addinKey, 'CommandLineSafe', 0);
  RegWriteStringValue(HKCU, addinKey, 'Location', dllPath);

  // DoNotDisableAddinList: prevents Excel from flipping LoadBehavior to 2
  // after any startup hiccup and silently hiding the add-in.
  resiliencyKey := 'Software\Microsoft\Office\16.0\Excel\Resiliency\DoNotDisableAddinList';
  RegWriteDWordValue(HKCU, resiliencyKey, progId, 1);
end;

procedure UnregisterExcelAddIn(const progId: string);
begin
  RegDeleteKeyIncludingSubkeys(HKCU, 'Software\Microsoft\Office\Excel\Addins\' + progId);
  RegDeleteKeyIncludingSubkeys(HKCU, 'Software\Microsoft\Office\16.0\Excel\Addins\' + progId);
  RegDeleteValue(HKCU, 'Software\Microsoft\Office\16.0\Excel\Resiliency\DoNotDisableAddinList', progId);
end;

procedure SnapshotPreviousExcelRegistration();
var
  addinKey: string;
begin
  addinKey := 'Software\Microsoft\Office\Excel\Addins\{#MainProgId}';
  PreviousRegistrationExists :=
    RegQueryStringValue(
      HKCU, 'Software\Classes\CLSID\{#MainClsid}\InprocServer32',
      'Assembly', PreviousMainAssembly) and
    RegQueryStringValue(
      HKCU, 'Software\Classes\CLSID\{#MainClsid}\InprocServer32',
      'CodeBase', PreviousMainCodeBase) and
    RegQueryStringValue(
      HKCU, 'Software\Classes\CLSID\{#TaskPaneClsid}\InprocServer32',
      'Assembly', PreviousTaskPaneAssembly) and
    RegQueryStringValue(
      HKCU, 'Software\Classes\CLSID\{#TaskPaneClsid}\InprocServer32',
      'CodeBase', PreviousTaskPaneCodeBase) and
    RegQueryStringValue(HKCU, addinKey, 'Description', PreviousAddinDescription) and
    RegQueryStringValue(HKCU, addinKey, 'FriendlyName', PreviousAddinFriendlyName) and
    RegQueryStringValue(HKCU, addinKey, 'Location', PreviousAddinLocation) and
    RegQueryDWordValue(HKCU, addinKey, 'LoadBehavior', PreviousLoadBehavior) and
    RegQueryDWordValue(HKCU, addinKey, 'CommandLineSafe', PreviousCommandLineSafe);
end;

procedure RestorePreviousExcelRegistration();
var
  addinKey: string;
begin
  RegisterComClass(
    '{#MainClsid}', '{#MainProgId}', PreviousMainCodeBase,
    '{#MainClass}', PreviousMainAssembly);
  RegisterComClass(
    '{#TaskPaneClsid}', '{#TaskPaneProgId}', PreviousTaskPaneCodeBase,
    '{#TaskPaneClass}', PreviousTaskPaneAssembly);

  RegisterExcelAddIn(
    '{#MainProgId}', PreviousAddinFriendlyName, PreviousAddinLocation);
  addinKey := 'Software\Microsoft\Office\Excel\Addins\{#MainProgId}';
  RegWriteStringValue(HKCU, addinKey, 'Description', PreviousAddinDescription);
  RegWriteDWordValue(HKCU, addinKey, 'LoadBehavior', PreviousLoadBehavior);
  RegWriteDWordValue(HKCU, addinKey, 'CommandLineSafe', PreviousCommandLineSafe);
end;

procedure RequireRegistryString(const rootKey: Integer; const key, name, expected: string);
var
  actual: string;
begin
  if (not RegQueryStringValue(rootKey, key, name, actual)) or (actual <> expected) then
    RaiseException('DeepExcel registry verification failed: HKCU\' + key + ' [' + name + ']');
end;

procedure RequireRegistryDWord(const key, name: string; expected: Cardinal);
var
  actual: Cardinal;
begin
  if (not RegQueryDWordValue(HKCU, key, name, actual)) or (actual <> expected) then
    RaiseException('DeepExcel registry verification failed: HKCU\' + key + ' [' + name + ']');
end;

procedure VerifyDeepExcelRegistration();
var
  dllPath: string;
begin
  dllPath := ExpandConstant('{app}') + '\' + '{#AddinDLL}';
  StringChangeEx(dllPath, '\', '/', True);
  dllPath := 'file:///' + dllPath;
  RequireRegistryString(HKCU64, 'Software\Classes\CLSID\{#MainClsid}\InprocServer32', 'CodeBase', dllPath);
  RequireRegistryString(HKCU32, 'Software\Classes\CLSID\{#MainClsid}\InprocServer32', 'CodeBase', dllPath);
  RequireRegistryString(HKCU64, 'Software\Classes\CLSID\{#MainClsid}\InprocServer32\{#AssemblyVersion}', 'CodeBase', dllPath);
  RequireRegistryString(HKCU32, 'Software\Classes\CLSID\{#MainClsid}\InprocServer32\{#AssemblyVersion}', 'CodeBase', dllPath);
  RequireRegistryString(HKCU64, 'Software\Classes\CLSID\{#TaskPaneClsid}\InprocServer32', 'CodeBase', dllPath);
  RequireRegistryString(HKCU32, 'Software\Classes\CLSID\{#TaskPaneClsid}\InprocServer32', 'CodeBase', dllPath);
  RequireRegistryString(HKCU64, 'Software\Classes\CLSID\{#TaskPaneClsid}\InprocServer32\{#AssemblyVersion}', 'CodeBase', dllPath);
  RequireRegistryString(HKCU32, 'Software\Classes\CLSID\{#TaskPaneClsid}\InprocServer32\{#AssemblyVersion}', 'CodeBase', dllPath);
  RequireRegistryString(HKCU64, 'Software\Classes\{#MainProgId}\CLSID', '', '{#MainClsid}');
  RequireRegistryString(HKCU32, 'Software\Classes\{#MainProgId}\CLSID', '', '{#MainClsid}');
  RequireRegistryDWord('Software\Microsoft\Office\Excel\Addins\{#MainProgId}', 'LoadBehavior', 3);
end;

procedure RunAndRequire(const fileName, parameters, description: string);
var
  resultCode: Integer;
begin
  if IsUninstaller() then
    UninstallProgressForm.StatusLabel.Caption := description
  else
    WizardForm.StatusLabel.Caption := description;
  if (not Exec(fileName, parameters, '', SW_HIDE, ewWaitUntilTerminated, resultCode)) or
     (resultCode <> 0) then
    RaiseException(description + ' failed (exit code ' + IntToStr(resultCode) + ').');
end;

function MoveFileEx(existingFile, newFile: string; flags: Cardinal): Boolean;
  external 'MoveFileExW@kernel32.dll stdcall';

// Inno offers no way to set Setup's exit code from [Code]. A post-install
// failure must not be reported as success, so the failure path ends here.
procedure ExitProcess(exitCode: Cardinal);
  external 'ExitProcess@kernel32.dll stdcall';

procedure UpdateWpsManifest(const mode: string);
var
  addinRoot, manifestPath, temporaryPath, backupPath: string;
  originalHash: string;
  originalExists, existsNow: Boolean;
  document, validationDocument, rootNode, nodes, entry: Variant;
begin
  addinRoot := ExpandConstant('{userappdata}\kingsoft\wps\jsaddons');
  manifestPath := addinRoot + '\publish.xml';
  temporaryPath := addinRoot + '\.publish.deepexcel.tmp';
  backupPath := manifestPath + '.bak';
  ForceDirectories(addinRoot);

  originalExists := FileExists(manifestPath);
  if originalExists then
    originalHash := GetSHA256OfFile(manifestPath)
  else
    originalHash := '';

  document := CreateOleObject('MSXML2.DOMDocument.6.0');
  document.async := False;
  document.resolveExternals := False;
  document.preserveWhiteSpace := False;
  if originalExists then
  begin
    document.load(manifestPath);
    if document.parseError.errorCode <> 0 then
    begin
      CopyFile(manifestPath, manifestPath + '.invalid.bak', False);
      RaiseException('Existing WPS publish.xml is invalid: ' + document.parseError.reason);
    end;
  end
  else
  begin
    document.loadXML('<?xml version="1.0" encoding="utf-8"?><jsplugins/>');
  end;

  rootNode := document.documentElement;
  if CompareText(rootNode.nodeName, 'jsplugins') <> 0 then
    RaiseException('Unexpected WPS manifest root (expected jsplugins).');

  nodes := rootNode.selectNodes('*[@name="DeepExcel"]');
  while nodes.length > 0 do
  begin
    rootNode.removeChild(nodes.item(0));
    nodes := rootNode.selectNodes('*[@name="DeepExcel"]');
  end;

  if CompareText(mode, 'Install') = 0 then
  begin
    entry := document.createElement('jsplugin');
    entry.setAttribute('name', 'DeepExcel');
    entry.setAttribute('type', 'et');
    entry.setAttribute('url', 'DeepExcel_{#AppVersion}');
    entry.setAttribute('version', '{#AppVersion}');
    entry.setAttribute('enable', 'enable_dev');
    entry.setAttribute('install', 'null');
    entry.setAttribute('customDomain', '');
    rootNode.appendChild(entry);
  end;

  DeleteFile(temporaryPath);
  document.save(temporaryPath);
  if not FileExists(temporaryPath) then
    RaiseException('WPS manifest temporary file was not created.');

  validationDocument := CreateOleObject('MSXML2.DOMDocument.6.0');
  validationDocument.async := False;
  validationDocument.resolveExternals := False;
  validationDocument.load(temporaryPath);
  if validationDocument.parseError.errorCode <> 0 then
  begin
    DeleteFile(temporaryPath);
    RaiseException('Generated WPS manifest is invalid: ' + validationDocument.parseError.reason);
  end;

  existsNow := FileExists(manifestPath);
  if existsNow <> originalExists then
  begin
    DeleteFile(temporaryPath);
    RaiseException('WPS publish.xml changed during update; please retry.');
  end;
  if originalExists and (GetSHA256OfFile(manifestPath) <> originalHash) then
  begin
    DeleteFile(temporaryPath);
    RaiseException('WPS publish.xml was modified by another process; please retry.');
  end;

  if originalExists and (not CopyFile(manifestPath, backupPath, False)) then
  begin
    DeleteFile(temporaryPath);
    RaiseException('Cannot back up WPS publish.xml.');
  end;

  { MOVEFILE_REPLACE_EXISTING | MOVEFILE_WRITE_THROUGH }
  if not MoveFileEx(temporaryPath, manifestPath, 1 or 8) then
  begin
    DeleteFile(temporaryPath);
    RaiseException('Cannot atomically replace WPS publish.xml.');
  end;
end;

// ---------------------------------------------------------------------------
// Full register / unregister
// ---------------------------------------------------------------------------
procedure RegisterDeepExcel();
var
  dllPath: string;
begin
  dllPath := ExpandConstant('{app}') + '\' + '{#AddinDLL}';
  RegisterComClass('{#MainClsid}', '{#MainProgId}', dllPath, '{#MainClass}', '{#AssemblyValue}');
  RegisterComClass('{#TaskPaneClsid}', '{#TaskPaneProgId}', dllPath, '{#TaskPaneClass}', '{#AssemblyValue}');
  RegisterExcelAddIn('{#MainProgId}', '{#AppName} AI AddIn', dllPath);
end;

procedure UnregisterDeepExcel();
begin
  UnregisterExcelAddIn('{#MainProgId}');
  UnregisterComClass('{#MainClsid}', '{#MainProgId}');
  UnregisterComClass('{#TaskPaneClsid}', '{#TaskPaneProgId}');
end;

// ---------------------------------------------------------------------------
// Events
// ---------------------------------------------------------------------------
function InitializeSetup(): Boolean;
var
  ec: Integer;
begin
  // Always register Excel. Some enterprise/MSI/non-default Office installs
  // omit App Paths; the old detection then silently skipped Excel while Setup
  // still reported success. Detection now controls only eager prerequisites.
  ExcelInstalled := IsExcelInstalled();
  ExcelEnabled := True;
  if ExcelInstalled then
    Log('Excel detected: True')
  else
    Log('Excel detected: False; Excel registration will still be installed.');
  SnapshotPreviousExcelRegistration();
  if ExcelInstalled and (not IsDotNet48Detected()) then
  begin
    MsgBox('DeepExcel 需要 .NET Framework 4.8。' + #13#10 +
           '请先安装 .NET 4.8 后再运行本安装程序。', mbCriticalError, MB_OK);
    ShellExec('open', 'https://dotnet.microsoft.com/download/dotnet-framework/net48', '', '', SW_SHOW, ewNoWait, ec);
    Result := False;
    Exit;
  end;

  // 2) Old machine-wide registration shadows the per-user one. Do not continue
  //    unless this process can clean it after the user accepts the wizard.
  if HklmResidualExists() then
  begin
    MsgBox('检测到旧版“机器级(管理员)”注册残留，它会覆盖本次用户级注册。' + #13#10 +
           '请让管理员先卸载旧版或清理旧版机器级注册，然后由当前用户正常运行本安装程序。' + #13#10 +
           '不要用另一个管理员账户运行本安装程序，否则会安装到错误的用户账户。', mbCriticalError, MB_OK);
    Result := False;
    Exit;
  end;

  // 3) WebView2 runtime warning (install is attempted after files are copied).
  if ExcelInstalled and (not IsWebView2Installed()) then
    MsgBox('未检测到 WebView2 运行时，安装程序将自动为您安装（需联网）。' + #13#10 +
           '若离线环境安装失败，请先手动安装“Microsoft Edge WebView2 Runtime”。', mbInformation, MB_OK);

  Result := True;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  errorMessage: string;
  wpsActivated: Boolean;
begin
  if CurStep = ssPostInstall then
  begin
    wpsActivated := False;
    try
      if ExcelEnabled then
      begin
        if ExcelInstalled and WebView2NeedsInstall() then
          RunAndRequire(
            ExpandConstant('{tmp}\MicrosoftEdgeWebview2Setup.exe'),
            '/silent /install',
            '正在安装 WebView2 运行时');
        if ExcelInstalled and (not IsWebView2Installed()) then
          RaiseException('WebView2 Runtime installation did not complete successfully.');

        RegisterDeepExcel();
        VerifyDeepExcelRegistration();
        // DeepExcel.Repair.exe replaces the two powershell.exe hops that used
        // to run register-user.ps1 here. Native tooling keeps powershell.exe
        // out of the install critical path: it was both a hard dependency on
        // the user's PowerShell environment and a textbook antivirus heuristic
        // hit (unsigned process -> HKCU\...\Office\Excel\Addins). It performs
        // the work Inno's [Code] cannot: clearing Excel's binary DisabledItems
        // values, stripping Mark-of-the-Web, and 64-bit COM activation.
        RunAndRequire(
          ExpandConstant('{app}\DeepExcel.Repair.exe'),
          '--repair --quiet',
          '正在校验并修复 Excel 加载项状态');
        // A process can only activate COM in its own bitness, so 32-bit Office
        // support needs a genuinely 32-bit probe.
        RunAndRequire(
          ExpandConstant('{app}\DeepExcel.Probe32.exe'),
          '--activation-only',
          '正在验证 32 位 Excel 加载器');
        VerifyDeepExcelRegistration();
      end;

    except
      errorMessage := GetExceptionMessage();
      if ExcelEnabled then
      begin
        if PreviousRegistrationExists then
          RestorePreviousExcelRegistration()
        else
          UnregisterDeepExcel();
      end;
      // Do NOT re-raise. Inno treats an exception from CurStepChanged as
      // non-fatal: it logs "CurStepChanged raised an exception", continues to
      // ssDone, and Setup still returns exit code 0. Verified with a minimal
      // probe .iss -- the exit code was 0 even though the post-install step had
      // failed and the registration above was rolled back.
      //
      // That is how a fresh-machine install could report success while leaving
      // Excel with no add-in registered: exactly the v0.4.11..v0.4.17 failure
      // mode, hidden behind a successful exit code. Silent/IT deployments and
      // CI see only the exit code, so it has to tell the truth.
      PostInstallFailed := True;
      PostInstallError := errorMessage;
      Log('Excel post-install step failed; Excel registration rolled back: ' + errorMessage);
    end;

    // WPS is activated in its own try block, NOT chained after the Excel work.
    //
    // The WPS add-in is plain JS: no COM, no .NET, no bitness, nothing it needs
    // from the Excel side. It used to sit at the end of the Excel try block, so
    // any Excel-side failure skipped it entirely -- the files were copied (the
    // [Files] section is unconditional) but publish.xml never learned about
    // them, and WPS silently loaded nothing. On a machine with no Excel at all,
    // that made the WPS add-in unreachable for a reason that has nothing to do
    // with WPS.
    //
    // The old ordering comment argued WPS must come last so a committed
    // publish.xml can never point at rolled-back files. That still holds: the
    // rollback above only touches Excel's COM registration, and the payload in
    // jsaddons is left in place on failure (Setup now exits non-zero instead of
    // unwinding the file copy), so the manifest never dangles.
    try
      WizardForm.StatusLabel.Caption := '正在启用 WPS 表格加载项';
      UpdateWpsManifest('Install');
      wpsActivated := True;
    except
      errorMessage := GetExceptionMessage();
      Log('WPS activation failed: ' + errorMessage);
      if not PostInstallFailed then
      begin
        PostInstallFailed := True;
        PostInstallError := errorMessage;
      end;
    end;
  end
  else if CurStep = ssDone then
  begin
    InstallCompleted := True;

    if PostInstallFailed then
    begin
      if not WizardSilent then
        MsgBox('DeepExcel 安装未完成。' + #13#10 + #13#10 +
               PostInstallError + #13#10 + #13#10 +
               '已撤销本次注册，Excel 不会加载到半配置的加载项。' + #13#10 +
               '请从「开始菜单 → DeepExcel → DeepExcel 诊断与修复」查看详细诊断。',
               mbCriticalError, MB_OK);
      // ExitProcess is the only way to return a non-zero code from here; Inno
      // has no API to set one. Verified by probe: the log is fully flushed
      // before the process ends, so /LOG output stays complete.
      Log('Exiting with code 4 (fatal error during installation).');
      ExitProcess(4);
    end;

    // The final note belongs here, not in DeinitializeSetup.
    //
    // DeinitializeSetup runs as Setup is tearing down, after the wizard form is
    // gone. Showing a message box from there produced "Floating point
    // underflow." on a real install -- the install itself had already succeeded
    // ("Installation process succeeded." in the log), so the only visible effect
    // was a crash-looking dialog at the very end. For an unsigned installer the
    // user has already had to click through SmartScreen; ending on that box
    // makes a successful install look broken.
    if not WizardSilent then
      MsgBox('DeepExcel 安装完成！' + #13#10 + #13#10 +
             '请关闭并重新打开 Excel 或 WPS 表格，' + #13#10 +
             '在功能区（Ribbon）中找到“DeepExcel”选项卡即可使用。', mbInformation, MB_OK);
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usUninstall then
  begin
    UninstallProgressForm.StatusLabel.Caption := '正在移除 WPS 表格加载项';
    UpdateWpsManifest('Uninstall');
    UnregisterDeepExcel();
  end;
end;

// DeinitializeSetup is deliberately absent.
//
// It runs after the wizard form has been destroyed, so anything touching the UI
// from there is operating on a torn-down window. The completion notice that used
// to live here now runs in CurStepChanged(ssDone), while the form is still alive.
