"""shared skills

Revision ID: 795b199bc72d
Revises: 0632f77541a7
Create Date: 2026-09-12 19:24:03.404459
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '795b199bc72d'
down_revision: Union[str, None] = '0632f77541a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('document', sa.Text(), nullable=False),
    sa.Column('share_code', sa.String(length=32), nullable=True),
    sa.Column('import_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'skill_id', name='uq_owner_skill')
    )
    with op.batch_alter_table('shared_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_skills_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_skills_share_code'), ['share_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_shared_skills_skill_id'), ['skill_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_skills_skill_id'))
        batch_op.drop_index(batch_op.f('ix_shared_skills_share_code'))
        batch_op.drop_index(batch_op.f('ix_shared_skills_owner_id'))

    op.drop_table('shared_skills')
    # ### end Alembic commands ###
