#requires -Version 5.1
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet('Install', 'Uninstall')]
    [string]$Mode,

    [Parameter(Mandatory = $true)]
    [ValidatePattern('^[0-9]+(\.[0-9]+){1,3}$')]
    [string]$Version
)

$ErrorActionPreference = 'Stop'
$addinRoot = Join-Path $env:APPDATA 'kingsoft\wps\jsaddons'
$manifestPath = Join-Path $addinRoot 'publish.xml'
$originalManifestExists = Test-Path -LiteralPath $manifestPath -PathType Leaf
$originalManifestHash = $null
if ($originalManifestExists) {
    $originalManifestHash = (Get-FileHash -LiteralPath $manifestPath -Algorithm SHA256).Hash
}

if (-not (Test-Path -LiteralPath $addinRoot)) {
    New-Item -ItemType Directory -Path $addinRoot -Force | Out-Null
}

$document = New-Object System.Xml.XmlDocument
$document.PreserveWhitespace = $false
if (Test-Path -LiteralPath $manifestPath) {
    try {
        $document.Load($manifestPath)
    } catch {
        $backup = "$manifestPath.invalid-$(Get-Date -Format yyyyMMddHHmmss).bak"
        Copy-Item -LiteralPath $manifestPath -Destination $backup -Force
        throw "Existing WPS publish.xml is invalid. Backup created at $backup. $($_.Exception.Message)"
    }
} else {
    $declaration = $document.CreateXmlDeclaration('1.0', 'UTF-8', $null)
    [void]$document.AppendChild($declaration)
    [void]$document.AppendChild($document.CreateElement('jsplugins'))
}

if (-not $document.DocumentElement -or $document.DocumentElement.Name -ne 'jsplugins') {
    throw "Unexpected WPS manifest root in $manifestPath (expected <jsplugins>)."
}

@($document.DocumentElement.ChildNodes) |
    Where-Object { $_.NodeType -eq [System.Xml.XmlNodeType]::Element -and $_.GetAttribute('name') -eq 'DeepExcel' } |
    ForEach-Object { [void]$document.DocumentElement.RemoveChild($_) }

if ($Mode -eq 'Install') {
    $entry = $document.CreateElement('jsplugin')
    $entry.SetAttribute('name', 'DeepExcel')
    $entry.SetAttribute('type', 'et')
    # Match the offline publish.xml generated by the official wpsjs tool.
    # WPS resolves this relative folder below %APPDATA%\kingsoft\wps\jsaddons;
    # "file://" is not a valid local-package entry and leaves the payload
    # installed but undiscoverable.
    $entry.SetAttribute('url', "DeepExcel_$Version")
    $entry.SetAttribute('version', $Version)
    $entry.SetAttribute('enable', 'enable_dev')
    $entry.SetAttribute('install', 'null')
    $entry.SetAttribute('customDomain', '')
    [void]$document.DocumentElement.AppendChild($entry)
}

$settings = New-Object System.Xml.XmlWriterSettings
$settings.Encoding = New-Object System.Text.UTF8Encoding($false)
$settings.Indent = $true
$settings.NewLineChars = "`r`n"
$tempPath = Join-Path $addinRoot ('.publish.xml.{0}.tmp' -f [Guid]::NewGuid().ToString('N'))
$backupPath = "$manifestPath.bak"
$writer = [System.Xml.XmlWriter]::Create($tempPath, $settings)
try {
    $document.Save($writer)
} finally {
    $writer.Dispose()
}

try {
    # Validate the completed temporary document before replacing a manifest that
    # may contain entries owned by other WPS add-ins.
    $validationDocument = New-Object System.Xml.XmlDocument
    $validationDocument.Load($tempPath)

    $manifestExistsNow = Test-Path -LiteralPath $manifestPath -PathType Leaf
    if ($manifestExistsNow -ne $originalManifestExists) {
        throw 'WPS publish.xml changed while it was being updated. Please retry.'
    }
    if ($originalManifestExists -and
        (Get-FileHash -LiteralPath $manifestPath -Algorithm SHA256).Hash -ne $originalManifestHash) {
        throw 'WPS publish.xml was modified by another process. No changes were applied; please retry.'
    }

    if ($originalManifestExists) {
        [System.IO.File]::Replace($tempPath, $manifestPath, $backupPath, $true)
        # File.Replace captures the exact destination that existed at replacement
        # time in the backup. If it differs from what we loaded, another writer
        # won the race after our pre-check; restore its version atomically.
        $replacedManifestHash = (Get-FileHash -LiteralPath $backupPath -Algorithm SHA256).Hash
        if ($replacedManifestHash -ne $originalManifestHash) {
            $conflictPath = "$manifestPath.deepexcel-conflict-$(Get-Date -Format yyyyMMddHHmmssfff).bak"
            [System.IO.File]::Replace($backupPath, $manifestPath, $conflictPath, $true)
            throw "WPS publish.xml changed during atomic replacement. The concurrent version was restored; retry installation."
        }
    } else {
        [System.IO.File]::Move($tempPath, $manifestPath)
    }
} finally {
    if (Test-Path -LiteralPath $tempPath) {
        Remove-Item -LiteralPath $tempPath -Force
    }
}

if ($Mode -eq 'Install') {
    # Activate the new manifest first. Only then remove older payloads owned by
    # DeepExcel. Cleanup is best-effort and must not turn a committed, valid
    # manifest into an installer failure. Never traverse a reparse point.
    try {
        Get-ChildItem -LiteralPath $addinRoot -Directory -Force -ErrorAction Stop |
            Where-Object { $_.Name -match '^DeepExcel_[0-9]+(\.[0-9]+){1,3}$' -and $_.Name -ne "DeepExcel_$Version" } |
            ForEach-Object {
                if ($_.Attributes -band [IO.FileAttributes]::ReparsePoint) {
                    Write-Warning "Skipped reparse-point WPS add-in directory: $($_.FullName)"
                } else {
                    Remove-Item -LiteralPath $_.FullName -Recurse -Force -ErrorAction Stop
                }
            }
    } catch {
        Write-Warning "The new WPS manifest is active, but an older DeepExcel payload could not be removed: $($_.Exception.Message)"
    }
}

Write-Host "WPS publish.xml updated: $Mode DeepExcel $Version"
